### ISSUE TITLE
.objmeta file creation

### ISSUE THREAD

**Issue by Ivan1pl** [MCME/MCME-RP-Manager#7]
Upon right click on a .obj file the option of creating an .objmeta should be available.

Syntax:
```yaml
texture: <texture name>
offset: <3 floats>
visibility: <integer>
parent: <model name>
omnidirectional_parent: <boolean>
```

Example:
```yaml
texture: "block/any_texture"
offset: -0.5 0.0 -0.5
visibility: 7
parent: "block/any_model"
omnidirectional_parent: True
```
